---
title: "midterm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## q6
```{r}
library("readr")
library("dplyr")
library("tidyr")

og=read.csv("murders.csv")
head(og)
#read data into 'og' dataframe and get a overview of the data manually.

new<-og %>%
  group_by(region) %>%
  mutate(murders=sum(total),population=sum(population)) %>%
  summarise(murders,population)
#Group the dataset by region, so that can calculate the total of murder counts and population of each region group. Store the result in 'new' dataset by regions.

new<-unique(new)
new
#Preserve only the unique values. That is, delete all the redundant subjects.

murder_rate<-new %>% 
  mutate(murder_rate=murders / population) %>%
#Create a new column that calculate the murder rate according to the definition of it
  arrange(murder_rate)
#Sort the data according to ascending order of the numeric value of the murder rates and restore the newly construct data in a new dataset 'murder_rate'.

murder_rate
```

## q7
```{r}
library("dplyr")
library("tidyr")
theme_set(theme_bw())

og=read.csv("antibiotic_wide.csv")
head(og)
#read data into 'og' dataframe and get a overview of the data manually.

right_species <- og %>% 
  pivot_longer(c(Unc05qi6,Unc06af7,Unc06g1h,Unc06grq,Unc09fy6,Unc06bhm), names_to = "species", values_to = "value")
#Know that latter 6 columns of the orginal dataset refers to values of that species of the corresponding sample. Then, use pivot_longer function to convert them into the right columns.

separate_sample_name <- right_species %>% 
  separate(sample, sep = "(?<=[A-Za-z])(?=[0-9])", into = c("ind", "time"), convert = TRUE, remove=FALSE)
#Know that the character part of the sample name->'ind', and the number part->'time', separate the 'sample' but preserve the original column, for better organization of data.

s=separate_sample_name
#make a copy of simpler name.

antibiotic_tidy <- s[order(s$ind,s$species),]
#The final version sort by the alphabetical order of 'ind', and then sort by species name 'species'.

antibiotic_tidy
```

## q8
```{r}
library("tidyverse")
library("zoo")
library("dplyr")
library("tidyr")
library("ggplot2")
library("RColorBrewer")
theme_set(theme_bw())

bike=read.csv("bike.csv")
head(bike)
#read data into 'bike' dataframe and get a overview of the data manually.

bike$hr <- as.numeric(as.character(bike$hr))
bike$count <- as.numeric(as.character(bike$count))
#make sure that the variables is numeric before graphing

ggplot(bike) +
  geom_line(aes(x = hr, y = count, col=as.factor(weekday), group=dteday)) +
  scale_color_brewer(palette = "Set1") +
  facet_wrap(~weekday) +
  theme(legend.position = "bottom")
```

##10
```{r}
library("tidyverse")
library("dplyr")
library("tidyr")
library("ggplot2")
library("RColorBrewer")
theme_set(theme_bw())

bike=read.csv("bike.csv")
head(bike)
#read data into 'bike' dataframe and get a overview of the data manually.

bike$hr <- as.numeric(as.character(bike$hr))
bike$count <- as.numeric(as.character(bike$count))
#make sure that the variables is numeric before graphing

separate_year <- bike %>% 
  separate(dteday,into = c("year", "day"), convert = TRUE, remove=FALSE)
separate_year[3]=NULL
#Separate the 'dteday' but only preserve the year variable

sum<- separate_year %>%
  group_by(year, weekday, hr) %>%
  summarize(lower = quantile(count, probs = .25),
            upper = quantile(count, probs = .75))

sum
#The required dataset
```

## q11
```{r}
library("tidyverse")
library("zoo")
library("dplyr")
library("tidyr")
library("ggplot2")
library("RColorBrewer")
theme_set(theme_bw())

bike=read.csv("bike.csv")
head(bike)
#(same as q10)

bike$hr <- as.numeric(as.character(bike$hr))
bike$count <- as.numeric(as.character(bike$count))
#(same as q10)

separate_year <- bike %>% 
  separate(dteday,into = c("year", "day"), convert = TRUE, remove=FALSE)
separate_year[3]=NULL
#(same as q10)

sum <- separate_year %>%
  group_by(year, weekday, hr) %>%
  summarize(lower = quantile(count, probs = .25),
            upper = quantile(count, probs = .75))
#(same as question10)

sum <- sum %>%
  mutate(year=as.character(year))
#Make sure the 'year' variable is the right format.

ggplot() +
  geom_line(data=bike, aes(x = hr, y = count, group=dteday),alpha=0.1) +
  geom_ribbon(data=sum, aes(x=hr, ymin=lower, ymax=upper, fill=year)) +
  facet_wrap(~weekday) +
  theme(legend.position = "bottom")
```

